### ISSUE TITLE
Elección del lenguaje de programación

### ISSUE THREAD

**Issue by pluque01** [carlosservi/Asistente_Ruta_Camioneros#12]
Hola! Voy a trabajar sobre tu proyecto. ¿Qué lenguaje te gustaría que usase?

**Comment by carlosservi** [comment]
Buenas, bienvenido al proyecto. Podemos usar Go si te parece bien, ya que cumple bastante bien los requisitos que nos comentó el profesor. Un saludo

**Comment by pluque01** [comment]
Perfecto entonces :))
