### ISSUE TITLE
Se debe crear una entidad capaz de almacenar la información relevante a "área de descanso"

### ISSUE THREAD

**Issue by pluque01** [carlosservi/Asistente_Ruta_Camioneros#14]
Se debería crear una clase que almacenase la información base sobre las áreas de descanso para satisfacer #9. 
Es importante tener en cuenta los horarios del área de descanso. ¿Son los mismos cada semana? ¿En qué fiestas cierran? ¿Tienen descansos a lo largo del día?

Por otro lado será necesario poder identificar a las áreas de descanso para distinguirlas entre sí.

**Comment by pluque01** [comment]
Completado en e6dd312

**Comment by JJ** [comment]
El commit que "cierra" este issue
* No explica por qué ha tomado esa decisión
* No sigue las mejores prácticas en los nombres de las variables. ¿Qué es Day?

No se ha planteado ningún problema, en realidad. Si el enunciado es "crear una entidad" cualquier entidad que se cree lo soluciona. En un planteamiento del problema tendrías que tener en cuenta qué son las horas de cierre, preguntándose cosas como si son las mismas todos los días, si se cierran en días de fiesta, cosas así. En un momento determinado y por simplicidad se puede escoger no tener en cuenta algo (como que cierren por la fiesta local de Pontevedra), pero el planteamiento de un problema debe tener en cuenta todos sus aspectos.
