### ISSUE TITLE
Se debe conocer el tiempo de llegada a cada una de las áreas de descanso

### ISSUE THREAD

**Issue by pluque01** [carlosservi/Asistente_Ruta_Camioneros#16]
Para cumplir con lo que nos pide el usuario en #9 y según lo debatido en #13, se debe conocer el tiempo de llegada a las áreas de descanso para que el conductor tenga tiempo de llegar. Hay que tener en cuenta si este tiempo va a representar como un transcurso de tiempo (para lo que haría falta conocer si es un tiempo absoluto o relativo) o como un instante determinado (para lo que haría falta conocer el tiempo de salida).

Otro aspecto a tener en cuenta es que el desplazarse a un área de servicio introduce un desvío de la ruta principal.

**Comment by JJ** [comment]
Dos cosas:
* Los issues siempre tienen que plantear un problema
* No se pueden cerrar hasta que no se fusionen, y siempre desde un commit o desde un PR fusionado.

**Comment by JJ** [comment]
¿Qué ocurre si un área de servicio está cerrada?
